### ISSUE TITLE
ITests failing on running job 'Initialize Language Servers for pom.xml'

### ISSUE THREAD

**Issue by vprusa** [fabric8-analytics/fabric8-analytics-devstudio-plugin#169]
Itests hangs on
15:44:25 10:44:24.597 DEBUG [WorkbenchTestable][JobIsRunning]   job 'Initialize Language Servers for pom.xml' has no excuses, wait for it 
.. For all test cases which opens pom.xml

[jenkins job](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics.itests/115/console)

Locally all test passed

I need to debug this with lsp4e for more info

**Comment by vprusa** [comment]
Using remote debug i was able to Generate Stack Report result even when job "Initialize Language Servers for pom.xml" was still running.  Forther attempts to stop job using UI button in Progress tab got this job stuck at state "Cancel Requested" as seen in screenshot.
![image](https://user-images.githubusercontent.com/2094946/37980031-5e368fc6-31ea-11e8-9062-edcfbfcb9f4e.png)

**Comment by rawagner** [comment]
Generate Stack Report and Language Servers are two independent features.

Can you please generate and attach here a java tread dump when the Initialize LS job is stuck ? See https://access.redhat.com/solutions/18178

**Comment by vprusa** [comment]
I am not sure if this is related but new error in [logs](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics.itests/jdk=openjdk-1.8,label=fedora26/43/console)
```
16:42:03 Error: Cannot find module '/mnt/hudson_workspace/workspace/fabric8-analytics.itests/jdk/openjdk-1.8/label/fedora26/sources/tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/target/work/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui_0.0.1.v20180208-1249/server/server.js'
16:42:03     at Function.Module._resolveFilename (module.js:470:15)
16:42:03     at Function.Module._load (module.js:418:25)
16:42:03     at Module.runMain (module.js:605:10)
16:42:03     at run (bootstrap_node.js:427:7)
16:42:03     at startup (bootstrap_node.js:148:9)
16:42:03     at bootstrap_node.js:542:3
```

**Comment by rawagner** [comment]
@vprusa So the LSP server.js is not downloaded during the build. download-maven-plugin plugin is used to download the LSP server and the plugin execution is skipped if skipRequirements is set to true (the value is inherited from skipTests), which it is in your jenkins job. I have added skipRequirements=false. Lets see if it helps
