### ISSUE TITLE
Cannot run language server if the Eclipse's path contains spaces

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#44]
When the installation directory of Eclipse contains spaces in its name, the server will fail to start because of the following exception:

``
java.net.URISyntaxException: Illegal character in path at index 36: file:/home/ljelinko/programs/jbt/4.5 + F8/../../../git/fabric8-analytics-devstudio-plugin/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/fabric8-analytics-lsp-server-test-devstudio/output/server.js
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:946)
	at com.redhat.fabric8analytics.lsp.eclipse.ui.Fabric8AnalyticsStreamConnectionProvider.<init>(Fabric8AnalyticsStreamConnectionProvider.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:102)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.<init>(ProjectSpecificLanguageServerWrapper.java:142)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrapperForConnection(LanguageServiceAccessor.java:199)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:163)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:261)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
``

**Comment by ljelinkova** [comment]
It seems this is an internal Eclipse issue with FileLocator.resolve(). This workaround works for me.


Bundle bundle = Platform.getBundle(Fabric8AnalysisLSUIActivator.PLUGIN_ID);

File serverFile = new File(FileLocator.getBundleFile(bundle), "/fabric8-analytics-lsp-server-test-devstudio/output/server.js");

setCommands(Arrays.asList(new String[] {
		nodeJsLocation.getAbsolutePath(),
		serverFile.getAbsolutePath(),

**Comment by ljelinkova** [comment]
This one should be closed by the commit.
